### ISSUE TITLE
Add more test files and reorganise data directory

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler-test-data#27]
As we now have well over 100 files, I think it's a good time to split up the data directory to have some sub-directories to categorise the test files.
I propose the following directories:
- METADATA
- ENTITIES
- GLOBALS
- OTHER

This is currently just a rough idea which will be worked on.

**Comment by HolterPhylo** [comment]
Thinking...

**Comment by monkeyman192** [comment]
So basically keep everything in the same structure it is in in the games files?

**Comment by HolterPhylo** [comment]
Just the
![Screenshot - 2020-10-02 , 17_45_16](https://user-images.githubusercontent.com/3037251/94978999-5170b300-04ee-11eb-91db-21169b0166bc.png)
 level 1 structure, unless you plan in having thousand of them there, like:

**Comment by monkeyman192** [comment]
Ah, I see what you mean. Yep, I think that is a good idea!

**Comment by hazardousmedic** [comment]
I think the folder structure and index file have accomplished this pretty well. Did you have anything else in mind for organization?

**Comment by monkeyman192** [comment]
Nope, looks good I think! I'll close this thanks 😄
