### ISSUE TITLE
Add automated script for generating a compact set of mbins

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler-test-data#3]
We need a script or set of scripts which are able to be given the path to a folder, and using this information, provide a list of filenames, or even copy the the files themselves into the `data` directory so that the files can be easily pushed to github.

This script should be given at least the following two arguments:
 - `filepath`: The path to either the folder containing extracted files, or the unpacked PCBANKS folder.
It might be better to assume the user has already unpacked all the files?
 - `version`: The verison of NMS (according to the steam ID) that the files are for. This will be written to `.version`
As part of this we can remove the `_ignore.txt` file

**Comment by hazardousmedic** [comment]
I don't know how you have it set up on your end, but when I unpack a new experimental I name the folder by Build ID. Can this be incorporated into your script? Porting the name of the containing folder as the replacement Build ID for `.version`

**Comment by monkeyman192** [comment]
oh, this should probably be closed already. I think the python script I added covers this already :)
